[project]
name = 'Dark-Matter-Mapping-Initiative'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-computing-integration]
path = 'contracts/quantum-computing-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-management]
path = 'contracts/research-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
